---
abstract: 'Manage CPAN Testers configuration data'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Testers-Config
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  CPAN::Testers::Config:
    file: lib/CPAN/Testers/Config.pm
    version: 0.002
requires:
  Carp: 0
  Data::Dumper: 0
  File::Basename: 0
  File::HomeDir: 0
  File::Path: 0
  File::Spec: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/cpan-testers-config/issues
  homepage: https://metacpan.org/release/CPAN-Testers-Config
  repository: git://github.com/dagolden/cpan-testers-config.git
version: 0.002
