---
abstract: 'Manage CPAN Testers configuration data'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.102160'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Testers-Config
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  CPAN::Testers::Config:
    file: lib/CPAN/Testers/Config.pm
    version: 0.001
requires:
  Carp: 0
  Data::Dumper: 0
  File::Basename: 0
  File::HomeDir: 0
  File::Path: 0
  File::Spec: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=CPAN-Testers-Config
  homepage: http://github.com/dagolden/cpan-testers-config/tree
  repository: git://github.com/dagolden/cpan-testers-config.git
version: 0.001
